// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgXjHrHYAHzWln8aU8y2fVBYFy69xOw4o',
    appId: '1:116834234380:web:a06d7202511c7017587e29',
    messagingSenderId: '116834234380',
    projectId: 'authtutorial-97a65',
    authDomain: 'authtutorial-97a65.firebaseapp.com',
    storageBucket: 'authtutorial-97a65.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQGR4pmb4MWY5747nj9eWXiCVeQAn9mA',
    appId: '1:116834234380:android:a25bab40730fc6c0587e29',
    messagingSenderId: '116834234380',
    projectId: 'authtutorial-97a65',
    storageBucket: 'authtutorial-97a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu6IsKu1U0QVt_OIYcnyS5y9AW7Awm-dA',
    appId: '1:116834234380:ios:c44eecb07c1efa3a587e29',
    messagingSenderId: '116834234380',
    projectId: 'authtutorial-97a65',
    storageBucket: 'authtutorial-97a65.firebasestorage.app',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu6IsKu1U0QVt_OIYcnyS5y9AW7Awm-dA',
    appId: '1:116834234380:ios:c44eecb07c1efa3a587e29',
    messagingSenderId: '116834234380',
    projectId: 'authtutorial-97a65',
    storageBucket: 'authtutorial-97a65.firebasestorage.app',
    iosBundleId: 'com.example.authenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgXjHrHYAHzWln8aU8y2fVBYFy69xOw4o',
    appId: '1:116834234380:web:5273d89287683f93587e29',
    messagingSenderId: '116834234380',
    projectId: 'authtutorial-97a65',
    authDomain: 'authtutorial-97a65.firebaseapp.com',
    storageBucket: 'authtutorial-97a65.firebasestorage.app',
  );
}
